### ISSUE TITLE
Use resources not labels [-4]

### ISSUE THREAD

**Issue by skodapetr** [DonRiccardo/UvoddoDatovehoInzenyrstvi#2]
```
ns1:county "Rychnov nad Kněžnou"^^xsd:string ;
ns1:region "Královéhradecký kraj"^^xsd:string ;
```
Zde měla být použitá IRI těch krajů/okresů/..., nikoliv názvy. 
Navíc to ani nesedí na rang, který definujete u těch predikátů.

**Comment by DonRiccardo** [comment]
Opravené na IRI.

**Comment by skodapetr** [comment]
To samé platí pro ns2:specialist, vlastně vše kde identifikujete nějaký koncept/věc by mělo být resource. Zejména pokud na to chcete odkazovat z více míst, což je klasicky pravda pro dimenze.

**Comment by DonRiccardo** [comment]
ns2:specialist taktiež opravený.
